# Generated by Django 3.1.4 on 2020-12-21 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
    ]
