# Generated by Django 3.1.4 on 2020-12-21 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Home', '0002_auto_20201221_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-pk']},
        ),
    ]
